name: carp_core
description: The CARP Flutter domain model. The core domain model used across all CARP Flutter plugins.
version: 0.1.3
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_core

environment:
  sdk: ">=2.0.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^1.0.0
  device_info: ^0.2.1
  json_annotation: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^1.0.0


# The following section is specific to Flutter.
flutter:
