name: carp_mobile_sensing
description: Mobile Sensing Framework for Flutter. A software framework for collecting sensor data from the phone and attached wearable devices via probes. Can be extended.
version: 0.5.1
author:  CACHET Team <cph.cachet@gmail.com>
homepage: https://github.com/cph-cachet/carp.sensing-flutter/tree/master/carp_mobile_sensing


environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #util plugins
  system_info: ^0.1.0
  uuid: ^1.0.0
  async: ^2.0.8
  device_info: ^0.4.0
  json_annotation: ^2.0.0
  path_provider: ^0.5.0
  archive: ^2.0.4

  # probe-dependent plugins
  sensors: ^0.4.0
  battery: ^0.3.0
  connectivity: ^0.4.0
  flutter_blue: ^0.5.0    # For bluetooth scan - v.0.5.0 supports AndroidX
  stats: ^0.2.0           # For calculating statistics, ex LightProbe

  # the CACHET plugins
  pedometer: ^0.0.5       # Get the step count from local OS
  light: ^0.1.0           # Light sensor over platform channel
  device_apps: ^1.0.0     # Device installed apps over platform channel
  screen_state: ^0.1.0    # Screen LOCK/ON/OFF
  app_usage: ^0.1.0       # App-usage statistics


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable: ^2.0.0
  test:


# The following section is specific to Flutter.
flutter:

